volumes:
  minio_activities:
  activities_pdata:
  redis_data:
    driver: local
  mongo_data:
  es_data:

services:
  minio:
    image: minio/minio:latest
    container_name: experiments_minio
    ports:
      - '9001:9001'
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - CONSOLE_ACCESS_KEY=test
      - CONSOLE_SECRET_KEY=test
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - minio_activities:/data

#  java-app:
#    image: mr3iscuit/activities:latest
#    container_name: activities_backend
#    ports:
#      - "9090:9090"
#    depends_on:
#      - minio
#      - mongodb
#    pull_policy: always
#    environment:
#      - SPRING_PROFILES_ACTIVE=compose
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-compose:5432/activities
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=12345678
#      - MINIO_URL=http://minio:9000
#      - MINIO_ACCESS_KEY=minioadmin
#      - MINIO_SECRET_KEY=minioadmin
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - REDIS_PASSWORD=redis
#      - MONGODB_URI=mongodb://mongodb:27017/activities
#      - MONGODB_USERNAME=bisco
#      - MONGODB_PASSWORD=biscobisco
#      - ELASTICSEARCH_URI=http://elasticsearch:9200

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    command: [ "redis-server", "--requirepass", "redis" ]
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=activities
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - es_data:/usr/share/elasticsearch/data
