spring:
  sql:
    init:
      mode: always
  application:
    name: activities
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activities
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

minio:
  url: http://localhost:9000
  presignedUrlExpiry: 5
  access:
    name: "minioadmin"
    secret: "minioadmin"
  bucket:
    name:
      event-background: event-background
    chunkSize: 10485760

