spring:
  sql:
    init:
      mode: always
  application:
    name: activities
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activities
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

minio:
  url: ${MINIO_URL}
  presignedUrlExpiry: 5
  default-buckets: event-background, category-icon, sub-category-icon
  access:
    name: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
    chunkSize: 10485760


  hello-world:
    name: ${HELLO_WORLD_NAME}
    age: ${HELLO_WORLD_AGE}
    address: ${HELLO_WORLD_ADDRESS}
    hobbies: ${HELLO_WORLD_HOBBIES}
    isActive: ${HELLO_WORLD_IS_ACTIVE}