spring:
  sql:
    init:
      mode: always
  application:
    name: activities
  data:
    mongodb:
#      username: bisco
#      password: biscobisco
#      host: localhost
#      port: 27017
#      database: activities
      uri: mongodb://admin:secretpassword@localhost:27017/activities?authSource=admin
  elasticsearch:
    uris: http://localhost:9200

redis:
  host: localhost
  port: 6379
  password: redis

minio:
  url: http://localhost:9000
  presignedUrlExpiry: 5
  default-buckets: event-background, category-icon, sub-category-icon
  access:
    name: "minioadmin"
    secret: "minioadmin"
    chunkSize: 10485760
server:
  port: 9090