spring:
  sql:
    init:
      mode: always
  application:
    name: activities
  data:
    mongodb:
      uri: ${MONGODB_URI}
      password: ${MONGODB_PASSWORD}
      username: ${MONGODB_USERNAME}
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

minio:
  url: ${MINIO_URL}
  presignedUrlExpiry: 5
  default-buckets: event-background, category-icon, sub-category-icon
  access:
    name: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
    chunkSize: 10485760
server:
  port: 9090