spring:
  sql:
    init:
      mode: always
  application:
    name: activities
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activities
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

redis:
  host: localhost
  port: 6379
  password: redis

minio:
  url: http://localhost:9000
  presignedUrlExpiry: 5
  default-buckets: event-background, category-icon, sub-category-icon
  access:
    name: "minioadmin"
    secret: "minioadmin"
    chunkSize: 10485760
server:
  port: 9090